services:
    sonarqube:
      image: sonarqube:latest
      environment:
        - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      ports:
        - "9000:9000"
      networks:
        - jenkins
      volumes:
        - sonarqube_data:/opt/sonarqube/data

networks:
  jenkins:
    driver: bridge

volumes:
  sonarqube_data: