jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://127.0.0.1:8080/
jobs:
  - script: >
      multibranchPipelineJob('itvb23ows-starter-code') {
          branchSources {
              git {
                  id = 'itvb23ows-starter-code'
                  remote('https://github.com/wilkebouwer/itvb23ows-starter-code')
              }
          }
      }
