pipeline {
    agent { docker { image 'php:8.3.0-alpine3.19' } }
    stages {
        stage('build') {
            steps {
                sh 'php --version'
            }
        }
        stage('SonarQube') {
             steps {
                 script { scannerHome = tool 'HiveGame SonarQube Scanner' }
                 withSonarQubeEnv('HiveGame SonarQube Scanner') {
                     sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=HiveGame"
                 }
             }
        }

    }
}
